# rocket launch
print("           /\\")
print("          |==|")
print("          |  |")
print("          |  |")
print("         /____\\")
print("        |      |")
print("        | NASA |")
print("        |      |")
print("        |      |")
print("       /|##||##|\\")
print("      / |##||##| \\")
print("     /  |##||##|  \\")
print("    |  / ^ || ^ \\  |")
print("    | /  ( || )  \\ |")
print("    |/   ( || )   \\|")
print("        (( || ))")
print("       ((  ||  ))")
print("      ((   ||   ))")
print("     ((    ||    ))")
print("    ((     ||     ))")
print("         ======")
print("         |  |")
print("         |  |")
print("         |  |")
print("        /____\\")
print("       |      |")
print("       | FIRE |")
print("       |______|")
print("       |______|")
print("        | || |")
print("        | || |")
print("       [======]")
print("        | || |")
print("        ====+=")

